[package]
name = "test-openbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openbook-v2-client = { path = "../openbook-v2/lib/client"}
